## The Basics

In [ ]:
import numpy as np

In [ ]:
list=[1,2,4]

In [ ]:
a = np.array([1,2,3], dtype='int8')
print(a)

[1 2 3]


In [ ]:
1.0

In [ ]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
b.dtype

dtype('float64')

In [ ]:
a.dtype

dtype('int8')

In [ ]:
2**64

18446744073709551616

In [ ]:
2**8

256

In [ ]:
c=np.array([184467440737, 1844674407370] , dtype='int64')

In [ ]:
00

8.0

In [ ]:
C=

In [ ]:
000
001
010
011
100
101
110
111

In [ ]:
0,1,2,3

In [ ]:
2**2

4

In [ ]:
01
10
11
00

SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers (<ipython-input-25-02a33d7089b9>, line 1)

In [ ]:
[1,2,3]
[1,35,5]
[4,5,6]

In [ ]:
d=np.array([[1,2,3], [1,35, 5], [5,6,7]])

In [ ]:
d.dtype

dtype('int64')

In [ ]:
1 = 64 bit

In [ ]:
64/8

8.0

In [ ]:
9*8

72

In [ ]:
d

array([[ 1,  2,  3],
       [ 1, 35,  5],
       [ 5,  6,  7]])

In [ ]:
d.shape

(3, 3)

In [ ]:
a.ndim

1

In [ ]:
d.ndim

2

In [ ]:
d.nbytes

72

In [ ]:
d.size

9

## 1.2 Accessing/changing Specific Elements, Row, Columns,

In [ ]:
a= np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]] , dtype='int8')

In [ ]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]], dtype=int8)

In [ ]:
b=np

In [ ]:
a[0:2 , 1:3]

array([[ 2,  3],
       [ 9, 10]], dtype=int8)

In [ ]:
a[1, 1:6:2]

array([ 9, 13], dtype=int8)

In [ ]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]], dtype=int8)

In [ ]:
0,0

In [ ]:
a.size

14

In [ ]:
a.shape

(2, 7)

x[r,c]

In [ ]:
a[1,4]

np.int8(12)

In [ ]:
a[1]

array([ 8,  9, 10, 11, 12, 13, 14], dtype=int8)

In [ ]:
a[ : , 2]

array([ 3, 10], dtype=int8)

In [ ]:
a[0, 1:6:2]

array([2, 4, 6], dtype=int8)

## 1.3 Initializing different types of arrays

In [ ]:
import numpy as np

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((2, 2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
np.ones((10,6), dtype='int32')

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]], dtype=int32)

In [ ]:
np.full((10,8), 34)

array([[34, 34, 34, 34, 34, 34, 34, 34],
       [34, 34, 34, 34, 34, 34, 34, 34],
       [34, 34, 34, 34, 34, 34, 34, 34],
       [34, 34, 34, 34, 34, 34, 34, 34],
       [34, 34, 34, 34, 34, 34, 34, 34],
       [34, 34, 34, 34, 34, 34, 34, 34],
       [34, 34, 34, 34, 34, 34, 34, 34],
       [34, 34, 34, 34, 34, 34, 34, 34],
       [34, 34, 34, 34, 34, 34, 34, 34],
       [34, 34, 34, 34, 34, 34, 34, 34]])

In [ ]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [ ]:
a.shape

(2, 7)

In [ ]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
np.random.rand(4,2)

array([[0.02294699, 0.68970315],
       [0.33171282, 0.09573478],
       [0.87957849, 0.10840152],
       [0.20352435, 0.97496855]])

In [ ]:
np.random.randint(1000, size=(10,10))

array([[408, 720, 385, 431, 897, 926, 423, 804, 907, 770],
       [ 91, 480, 804, 689, 154, 757, 504, 928, 184, 305],
       [562,  66, 762, 666, 168, 154,  83, 640, 919, 827],
       [351, 315, 746, 662, 360, 519,   7, 327, 315, 641],
       [741, 117, 497, 548, 474, 275, 789, 781, 955,  68],
       [756, 767, 811, 714, 963, 518, 885, 763, 447, 549],
       [446, 510, 102, 817, 869, 452, 732, 538, 793, 704],
       [502, 684, 791, 591,  17, 869, 602, 322, 183, 712],
       [687, 791, 950, 186, 641, 540, 870, 526, 182, 923],
       [ 52, 191, 796, 967, 478, 925, 956,  43, 473, 476]])

In [ ]:
np.random.randint(100, 1000, size=(10,10))

array([[684, 506, 585, 891, 512, 452, 673, 544, 339, 711],
       [406, 396, 984, 892, 470, 678, 682, 611, 665, 511],
       [112, 660, 609, 161, 526, 576, 525, 148, 269, 684],
       [536, 130, 511, 620, 544, 750, 687, 618, 772, 203],
       [668, 216, 844, 588, 511, 743, 881, 758, 304, 216],
       [998, 831, 272, 394, 987, 450, 735, 264, 308, 782],
       [664, 605, 806, 927, 587, 495, 718, 136, 558, 732],
       [701, 713, 173, 980, 454, 215, 267, 197, 427, 845],
       [647, 468, 531, 592, 880, 115, 107, 578, 207, 730],
       [354, 301, 460, 469, 700, 138, 800, 702, 966, 786]])

### Example

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
b = np.ones((5,5), dtype='int8')

In [ ]:
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [ ]:
b[1:4, 1:4]=0

In [ ]:
b

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [ ]:
b[2, 2]=9

In [ ]:
b

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

## Basic Mathematics

In [ ]:
c=np.array([1,2,3,4])

In [ ]:
##add
c+4


array([5, 6, 7, 8])

In [ ]:
c-3

array([-2, -1,  0,  1])

In [ ]:
d=c*4

In [ ]:
d

array([ 4,  8, 12, 16])

In [ ]:
c**2

array([ 1,  4,  9, 16])

In [ ]:
d+c

array([ 5, 10, 15, 20])

In [ ]:
np.cos(c)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [ ]:
np.sin(c)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [ ]:
n=np.full((10,10), 4)

In [ ]:
g=np.random.rand(10,10)

In [ ]:
np.sin(g)

array([[0.08485454, 0.22933613, 0.60553332, 0.74703959, 0.6640772 ,
        0.65281531, 0.07510603, 0.42511221, 0.30539765, 0.23551675],
       [0.16787597, 0.40486403, 0.16976339, 0.5494568 , 0.01264258,
        0.5463532 , 0.79170245, 0.554221  , 0.46915885, 0.05638535],
       [0.64184194, 0.25903594, 0.21703465, 0.65815714, 0.56790102,
        0.67161394, 0.62417127, 0.43850419, 0.54121081, 0.09786937],
       [0.77781165, 0.52806569, 0.62844692, 0.28337085, 0.61809167,
        0.50301577, 0.48297887, 0.09551704, 0.16961021, 0.71202394],
       [0.04530118, 0.52430578, 0.10410006, 0.40485666, 0.71787589,
        0.24772468, 0.31785198, 0.29988613, 0.30587904, 0.13959608],
       [0.4103136 , 0.09755751, 0.37326471, 0.65902598, 0.12727001,
        0.18522332, 0.05829573, 0.52148907, 0.69271194, 0.11888838],
       [0.72255415, 0.57845394, 0.69305051, 0.13072771, 0.5697815 ,
        0.69915136, 0.74867991, 0.756065  , 0.50907202, 0.75380396],
       [0.818029  , 0.16070685, 0.2993102

In [ ]:
np.cos(n)

array([[-0.65364362, -0.65364362, -0.65364362, -0.65364362, -0.65364362,
        -0.65364362, -0.65364362, -0.65364362, -0.65364362, -0.65364362],
       [-0.65364362, -0.65364362, -0.65364362, -0.65364362, -0.65364362,
        -0.65364362, -0.65364362, -0.65364362, -0.65364362, -0.65364362],
       [-0.65364362, -0.65364362, -0.65364362, -0.65364362, -0.65364362,
        -0.65364362, -0.65364362, -0.65364362, -0.65364362, -0.65364362],
       [-0.65364362, -0.65364362, -0.65364362, -0.65364362, -0.65364362,
        -0.65364362, -0.65364362, -0.65364362, -0.65364362, -0.65364362],
       [-0.65364362, -0.65364362, -0.65364362, -0.65364362, -0.65364362,
        -0.65364362, -0.65364362, -0.65364362, -0.65364362, -0.65364362],
       [-0.65364362, -0.65364362, -0.65364362, -0.65364362, -0.65364362,
        -0.65364362, -0.65364362, -0.65364362, -0.65364362, -0.65364362],
       [-0.65364362, -0.65364362, -0.65364362, -0.65364362, -0.65364362,
        -0.65364362, -0.65364362, -0.65364362

## statistics

In [ ]:
p=np.random.randint(100,10000, size=(10,100))

In [ ]:
stats=np.array([[1,2,3],[4,5,6]])

In [ ]:
p

array([[ 826, 6822, 9730, 3943, 4863, 1534, 5128, 4586, 1515, 6742, 8626,
        1193, 2567, 5446,  983, 1230, 5562,  772, 3860, 3625, 1692, 8188,
        6265, 1172, 2798, 4135, 3065, 5687, 7812, 7052, 9392, 4220, 5707,
        8369, 2464, 3819, 3221, 1026, 6200, 2337, 7547, 7942, 2473, 1763,
        8265, 7785, 6293, 3126, 6519,  287,  376, 6080, 8690, 7233,  693,
        5680, 2862, 9286, 1711, 1434, 5669, 4827, 6498, 4879,  110, 7851,
        7927, 5673, 6743, 2252, 7783, 7247, 9660, 5752, 4292, 7456, 7059,
        2830, 5846, 9195, 5167, 2347, 4462,  666, 7482, 3668, 3071, 8087,
        3246, 3158, 5680, 3338, 7457, 9369, 6265, 2330, 8249, 4616, 4224,
        1219],
       [ 309, 9050, 8440, 9110, 1826, 2287, 9227, 8605, 7013, 7516, 6310,
        5038, 9454, 1377,  835, 6574, 2942, 8084, 5848, 2084,  445, 1060,
        7648, 4938, 5771, 6569, 2629, 8743, 1457, 1032, 3666, 7734, 6181,
        2410, 1869,  485, 5984, 4037, 2541,  992, 3103, 3122, 9239, 6455,
        4801, 3811, 546

In [ ]:
np.min(p)

np.int64(110)

In [ ]:
np.max(p)

np.int64(9998)

## Reorganizing Array

In [ ]:
before=np.array([[1,2,3,4],[5,6,7,8]])

In [ ]:
before.shape

(2, 4)

In [ ]:
after=before.reshape(4,2)

In [ ]:
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
after=before.reshape(2,4)

In [ ]:
after

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [ ]:
v1=np.array([1,2,34,5])
v2=np.array([9,6,34,8])

In [ ]:
np.vstack([v1,v2])

array([[ 1,  2, 34,  5],
       [ 9,  6, 34,  8]])

In [ ]:
h1=np.array([1,2,34,5])
h2=np.array([9,6,34,8])

In [ ]:
np.hstack([h1,h2])

array([ 1,  2, 34,  5,  9,  6, 34,  8])